# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


class TestSendemail:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_sendemail(self):
        # Test name: send email
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://www.google.com.ua/")
        # 2 | setWindowSize | 1904x1045 |
        self.driver.set_window_size(1904, 1045)
        # 3 | click | css=.gb_Hd |
        self.driver.find_element(By.CSS_SELECTOR, ".gb_Hd").click()
        # 4 | type | id=identifierId | kininiiiii@gmail.com
        self.driver.find_element(By.ID, "identifierId").send_keys("kininiiiii@gmail.com")
        # 5 | click | css=.VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d |
        self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d").click()
        # 6 | mouseOver | css=.VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb |
        element = self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 7 | mouseOut | css=.VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb |
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 8 | type | name=Passwd | 555590nick
        self.driver.find_element(By.NAME, "Passwd").send_keys("555590nick")
        # 9 | click | css=.VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d |
        self.driver.find_element(By.CSS_SELECTOR, ".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-vQzf8d").click()
        # 10 | mouseOver | css=#gbwa .gb_d |
        element = self.driver.find_element(By.CSS_SELECTOR, "#gbwa .gb_d")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 11 | click | css=#gbwa .gb_d |
        self.driver.find_element(By.CSS_SELECTOR, "#gbwa .gb_d").click()
        # 12 | mouseOut | css=#gbwa .gb_d |
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 13 | selectFrame | index=0 |
        self.driver.switch_to.frame(0)
        # 14 | click | css=.u4RcUd > .j1ei8c:nth-child(7) .MrEfLc |
        self.driver.find_element(By.CSS_SELECTOR, ".u4RcUd > .j1ei8c:nth-child(7) .MrEfLc").click()
        # 15 | selectFrame | relative=parent |
        self.driver.switch_to.default_content()
        # 16 | click | css=.T-I-KE |
        self.driver.find_element(By.CSS_SELECTOR, ".T-I-KE").click()
        # 17 | click | id=:10p |
        self.driver.find_element(By.ID, ":10p").click()
        # 18 | type | id=:10p | nikolay.kirilov@zultys.com
        self.driver.find_element(By.ID, ":10p").send_keys("nikolay.kirilov@zultys.com")
        # 19 | click | id=:ww |
        self.driver.find_element(By.ID, ":ww").click()
        # 20 | type | id=:ww | test
        self.driver.find_element(By.ID, ":ww").send_keys("test")
        # 21 | click | id=:y5 |
        self.driver.find_element(By.ID, ":y5").click()
        # 22 | editContent | id=:y5 | test
        element = self.driver.find_element(By.ID, ":y5")
        self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'test'}",
                                   element)
        # 23 | click | id=:wm |
        self.driver.find_element(By.ID, ":wm").click()
        # 24 | mouseOver | css=.gb_Da |
        element = self.driver.find_element(By.CSS_SELECTOR, ".gb_Da")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 25 | click | css=.gb_Da |
        self.driver.find_element(By.CSS_SELECTOR, ".gb_Da").click()
        # 26 | mouseOut | css=.gb_Da |
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        # 27 | selectFrame | index=5 |
        self.driver.switch_to.frame(5)
        # 28 | click | css=.V5tzAf .SedFmc |
        self.driver.find_element(By.CSS_SELECTOR, ".V5tzAf .SedFmc").click()
        # 29 | selectFrame | relative=parent |
        self.driver.switch_to.default_content()
        # 30 | click | css=.JDAKTe:nth-child(3) .BHzsHc |
        self.driver.find_element(By.CSS_SELECTOR, ".JDAKTe:nth-child(3) .BHzsHc").click()
        # 31 | click | css=.n3x5Fb path |
        self.driver.find_element(By.CSS_SELECTOR, ".n3x5Fb path").click()
        # 32 | click | css=.qs41qe .RveJvd |
        self.driver.find_element(By.CSS_SELECTOR, ".qs41qe .RveJvd").click()
