# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRozetka():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rozetka(self):
    self.Open_main_page(Открытие_ссылки="https://rozetka.com.ua/")
    self.Open_page_in_full_mode()
    self.Find_platu_via_searching_filed(Поиск_1="Видеокарты")
    self.Scroll_and_find_matpaltu_via_searching_filed(Поиск_2="Материнские платы")
    self.Close_page()


  def Open_main_page(self, Открытие_ссылки):
    self.driver.get(Открытие_ссылки)

  def Open_page_in_full_mode(self):
    self.driver.set_window_size(1936, 1066)

  def Find_platu_via_searching_filed(self, Поиск_1):
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys(Поиск_1)
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)

  def Scroll_and_find_matpaltu_via_searching_filed(self, Поиск_2):
    self.driver.execute_script("window.scrollTo(0,6)")
    self.driver.execute_script("window.scrollTo(0,997)")
    self.driver.execute_script("window.scrollTo(0,1593)")
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys(Поиск_2)
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)

  def Close_page(self):
    self.driver.close()





  
