# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestYotube():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_yotube(self):
    self.driver.get("https://www.youtube.com/")
    self.driver.set_window_size(1904, 1045)
    self.driver.find_element(By.NAME, "search_query").click()
    self.driver.find_element(By.NAME, "search_query").send_keys("привет")
    self.driver.find_element(By.NAME, "search_query").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#search-clear-button .yt-spec-touch-feedback-shape__fill").click()
    self.driver.find_element(By.NAME, "search_query").click()
    self.driver.find_element(By.NAME, "search_query").send_keys("star wars")
    self.driver.find_element(By.NAME, "search_query").send_keys(Keys.ENTER)
  
