# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRozetka():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rozetka(self):
    self.driver.get("https://rozetka.com.ua/")
    self.driver.set_window_size(1936, 1066)
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("видеокарты")
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollTo(0,6)")
    self.driver.execute_script("window.scrollTo(0,997)")
    self.driver.execute_script("window.scrollTo(0,1593)")
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "search").send_keys("материнские платы")
    self.driver.find_element(By.NAME, "search").send_keys(Keys.ENTER)
    self.driver.close()
  
