# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKievtestzultyscom():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_kievtestzultyscom(self):
    # Test name: kiev-test.zultys.com
    # Step # | name | target | value
    # 1 | open | https://kiev-test.zultys.com/ | 
    self.driver.get("https://kiev-test.zultys.com/")
    # 2 | setWindowSize | 1920x1048 | 
    self.driver.set_window_size(1920, 1048)
    # 3 | click | css=a:nth-child(2) > button | 
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(2) > button").click()
    # 4 | click | id=mat-input-0 | 
    self.driver.find_element(By.ID, "mat-input-0").click()
    # 5 | type | id=mat-input-0 | nk1
    self.driver.find_element(By.ID, "mat-input-0").send_keys("nk1")
    # 6 | type | id=mat-input-1 | 1704nick
    self.driver.find_element(By.ID, "mat-input-1").send_keys("1704nick")
    # 7 | click | css=.mat-button-wrapper | 
    self.driver.find_element(By.CSS_SELECTOR, ".mat-button-wrapper").click()
    # 8 | click | css=.mat-button-wrapper | 
    self.driver.find_element(By.CSS_SELECTOR, ".mat-button-wrapper").click()
    # 9 | click | css=.mat-menu-trigger > svg circle | 
    self.driver.find_element(By.CSS_SELECTOR, ".mat-menu-trigger > svg circle").click()
    # 10 | click | //span[contains(text(),'Logout')] | 
    self.driver.find_element(By.XPATH, "//span[contains(text(),\'Logout\')]").click()
  
